name: Publish documentation
on:
  workflow_dispatch: # Run on-demand
    inputs:
      ref:
        description: Git ref to build docs from
        required: true
        default: main
        type: string
  release:
    types: [released] # Run when stable releases are published

jobs:
  push-branch:
    name: Build & push docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out from release
        if: github.event_name == 'release'
        uses: actions/checkout@v3
      - name: Check out from manual input
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn
      - run: yarn install
      - run: yarn build
      - name: Clone docs repo
        uses: actions/checkout@v3
        with:
          repository: oddbird/herman-docs
          ssh-key: ${{ secrets.DOCS_REPO_DEPLOY_KEY }}
          path: docs-repo
          ref: main
      - name: Commit & push to docs repo
        run: |
          SHA=$(git rev-parse HEAD)
          cd docs-repo
          rm -rf herman/docs
          cp -r ${{ github.workspace }}/docs herman/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit --allow-empty \
          -m "Update from https://github.com/${{ github.repository }}/commit/$SHA" \
          -m "Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git push origin
