name: Test
on:
  push:
  pull_request:
    types: [reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Just testing we can run commands"
