name: Upgrade dependencies

on:
  workflow_dispatch:
  # schedule:
  #   # Every Monday at 10:00 UTC
  #   - cron: '0 10 * * 1'

jobs:
  upgrade-python:
    name: Upgrade Python dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine Python version
        run: echo "PY_VERSION=$(grep -oP 'py\K(\d+\.\d+)' Dockerfile)" >> $GITHUB_ENV
      - uses: actions/setup-python@v2
        with:
          python-version: '${{ env.PY_VERSION }}'
          cache: pip
          cache-dependency-path: requirements/*.txt
      - name: Upgrade dependencies
        run: |
          pip install -U pip git+https://github.com/di/pip-tools.git@get-ci-green#egg=pip-tools
          pip-sync requirements/*.txt
          pip-compile --upgrade -o requirements/prod.txt requirements/prod.in
          pip-compile --upgrade -o requirements/dev.txt requirements/dev.in
      - uses: actions/upload-artifact@v2
        with:
          name: python-deps
          path: |
            requirements

  upgrade-js:
    name: Upgrade JS dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine node version
        run: echo "NODE_VERSION=$(grep -oP 'node\K\d+' Dockerfile)" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: yarn
      - name: Upgrade dependencies
        run: |
          yarn install
          yarn upgrade
      - uses: actions/upload-artifact@v2
        with:
          name: js-deps
          path: |
            package.json
            yarn.lock

  submit-pr:
    name: Submit pull request
    runs-on: ubuntu-latest
    needs: [upgrade-python, upgrade-js]
    steps:
      - uses: actions/checkout@v2
      - name: Download Python dependency changes
        uses: actions/download-artifact@v2
        with:
          name: python-deps
          path: requirements
      - name: Download JS dependency changes
        uses: actions/download-artifact@v2
        with:
          name: js-deps
      - name: Detect changes
        id: changes
        run: echo "::set-output name=count::$(git status --porcelain=v1 2>/dev/null | wc -l)"
      - name: Open pull request
        if: steps.changes.outputs.count > 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -B dependency-upgrades
          git add .
          git commit -m "Automated dependency upgrades"
          git push origin dependency-upgrades
          gh pr create \
          --title "Automated dependency upgrades" \
          --body "Full log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
